/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/scripts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every script, newest first
         * @description The sidebar's list.
         *
         *     No filtering by owner, because there is no owner: this deployment has one
         *     user and every script in the database belongs to them. When authentication
         *     lands, this grows a `WHERE user_id = ...` and the frontend does not change,
         *     because it was only ever asking "what can I see?" and the server was always
         *     the one answering.
         *
         *     Two queries, not N+1. The obvious implementation asks for the scripts and
         *     then loops asking each one for its latest run; with twenty scripts that is
         *     twenty-one round trips to render a list nobody scrolls.
         */
        get: operations["list_scripts_api_scripts_get"];
        put?: never;
        /** Upload a screenplay PDF */
        post: operations["create_script_api_scripts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scripts/{id}/scenes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Parsed scenes, with their elements */
        get: operations["get_scenes_api_scripts__id__scenes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scripts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Script metadata */
        get: operations["get_script_api_scripts__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Run
         * @description Start a run. Returns immediately; poll GET /api/runs/{id} or stream it.
         */
        post: operations["create_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Findings
         * @description Every finding, enriched enough to render without a second request.
         *
         *     `counts` is over the whole run rather than the returned page. A summary
         *     header that changed as you paged or filtered would be reporting the view
         *     rather than the script.
         */
        get: operations["get_findings_api_runs__run_id__findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download the clearance report
         * @description The run as the document a production actually files.
         *
         *     Deliberately unpaginated: this is the whole run, and a clearance report
         *     that stopped at finding 500 would be worse than no report, because it
         *     looks complete. `get_findings` caps at 2000 for a UI that renders rows
         *     into the DOM; nothing here renders anything until every row is in hand.
         *
         *     A run still in flight is refused rather than half-rendered. A partial
         *     report is indistinguishable from a finished one once it is a PDF on
         *     someone's desk, and this is the artefact most likely to be forwarded to
         *     somebody who was not watching the run.
         */
        get: operations["get_report_api_runs__run_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/findings/{finding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Record a review verdict
         * @description Accept, override or un-review one finding.
         *
         *     The combinations are checked here rather than trusted from the client.
         *     `overridden` without an `override_risk` would be a row claiming the
         *     reviewer disagreed while not saying what with, and `accepted` carrying an
         *     override would be a row that agrees and disagrees at once. Both are
         *     representable in the database and neither means anything, so both are
         *     refused.
         *
         *     Returns the whole enriched finding rather than an acknowledgement, so the
         *     list can replace one row from the response without refetching every
         *     finding in the run.
         */
        patch: operations["review_finding_api_findings__finding_id__patch"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApiErrorOut
         * @description Mirrors `ApiError` in the frontend, plus a machine-readable `code`.
         */
        ApiErrorOut: {
            /** Code */
            code: string;
            /** Detail */
            detail: string;
        };
        /** Body_create_script_api_scripts_post */
        Body_create_script_api_scripts_post: {
            /** File */
            file: string;
        };
        /**
         * FindingOut
         * @description One rated mention, with everything the review UI needs to show it.
         */
        FindingOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Element Id
             * Format: uuid
             * @description The MENTION id, on `elements`. Never a script_elements id.
             */
            element_id: string;
            /**
             * Risk
             * @enum {string}
             */
            risk: "red" | "amber" | "green";
            /** Rights Required */
            rights_required: string[];
            /** Rights Holders */
            rights_holders: components["schemas"]["RightsHolderOut"][];
            /** Rationale */
            rationale: string;
            /** Sources */
            sources: components["schemas"]["SourceOut"][];
            /** Alternatives */
            alternatives: string[];
            /**
             * Review Status
             * @enum {string}
             */
            review_status: "unreviewed" | "accepted" | "overridden";
            /** Override Risk */
            override_risk: ("red" | "amber" | "green") | null;
            /** Review Note */
            review_note: string | null;
            /** Reviewed At */
            reviewed_at: string | null;
            /** Created At */
            created_at: string;
            /** Canonical Name */
            canonical_name: string;
            /** Surface Form */
            surface_form: string;
            /**
             * Category
             * @enum {string}
             */
            category: "music" | "trademark" | "artwork" | "person" | "location" | "clip" | "literary" | "other";
            /**
             * Research Status
             * @enum {string}
             */
            research_status: "complete" | "partial" | "failed";
            /** Queries Run */
            queries_run: string[];
            /**
             * Script Element Id
             * Format: uuid
             */
            script_element_id: string;
            /** Char Start */
            char_start: number | null;
            /** Char End */
            char_end: number | null;
            /** Scene Number */
            scene_number: number;
            /** Page */
            page: number;
        };
        /**
         * FindingReviewIn
         * @description A reviewer's verdict on one finding.
         *
         *     The three states are not interchangeable and the combinations matter:
         *
         *         accepted    — the reviewer agrees with the rating as it stands.
         *                       An override_risk here would be contradictory.
         *         overridden  — the reviewer disagrees and supplies their own rating.
         *                       override_risk is required; without it the row would
         *                       claim a disagreement and not say what with.
         *         unreviewed  — undo. Clears the override, the note and the timestamp,
         *                       so a mistaken click leaves no trace behind.
         *
         *     Validated on the server rather than trusted from the client, because these
         *     rows are the record of who decided what, which is the part of a clearance
         *     report that matters if anyone ever asks.
         */
        FindingReviewIn: {
            /**
             * Review Status
             * @enum {string}
             */
            review_status: "unreviewed" | "accepted" | "overridden";
            /** Override Risk */
            override_risk?: ("red" | "amber" | "green") | null;
            /** Review Note */
            review_note?: string | null;
        };
        /** FindingsOut */
        FindingsOut: {
            /** Findings */
            findings: components["schemas"]["FindingOut"][];
            /** Total */
            total: number;
            /** @description red/amber/green counts across the WHOLE run, not the page. A summary header that changed when you paged would be a lie. */
            counts: components["schemas"]["RiskCountsOut"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * NoTextLayerOut
         * @description Mirrors `NoTextLayerError` — the one 422 the upload screen special-cases.
         *
         *     web/app/page.tsx reads `body.code` and shows a specific message telling
         *     the user to re-export, rather than the generic upload failure.
         */
        NoTextLayerOut: {
            /**
             * Code
             * @constant
             */
            code: "NO_TEXT_LAYER";
            /** Detail */
            detail: string;
            /** Pages Checked */
            pages_checked: number;
        };
        /** RightsHolderOut */
        RightsHolderOut: {
            /**
             * Role
             * @description publisher, master, estate, owner — or empty.
             */
            role: string;
            /** Name */
            name: string;
            /**
             * Confidence
             * @default medium
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
        };
        /**
         * RiskCountsOut
         * @description The three numbers the summary header shows.
         *
         *     A model rather than `dict`, for the same reason `FindingOut.category` is a
         *     Literal rather than `str`: a bare dict generates as
         *     `{[key: string]: unknown}` in TypeScript, so the component that renders
         *     `counts.red` stops type-checking and a renamed key becomes a blank space in
         *     the UI instead of a compile error.
         */
        RiskCountsOut: {
            /**
             * Red
             * @default 0
             */
            red: number;
            /**
             * Amber
             * @default 0
             */
            amber: number;
            /**
             * Green
             * @default 0
             */
            green: number;
        };
        /** RunCreateIn */
        RunCreateIn: {
            /**
             * Script Id
             * Format: uuid
             */
            script_id: string;
        };
        /** RunOut */
        RunOut: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Script Id
             * Format: uuid
             */
            script_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "extracting" | "researching" | "assessing" | "composing" | "complete" | "failed";
            progress: components["schemas"]["RunProgressOut"];
            /** Stats */
            stats: {
                [key: string]: unknown;
            };
            /** Started At */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Error */
            error: string | null;
        };
        /**
         * RunProgressOut
         * @description Counts the run header renders. Derived, not stored.
         *
         *     `runs` has no progress column; the frontend's RunHeader dereferences
         *     `run.progress.elements_found` unguarded, so this exists to keep that
         *     working rather than to add a column that would need maintaining in two
         *     places.
         */
        RunProgressOut: {
            /**
             * Elements Found
             * @default 0
             */
            elements_found: number;
            /**
             * Entities
             * @default 0
             */
            entities: number;
            /**
             * Findings
             * @default 0
             */
            findings: number;
            /**
             * Dossiers Complete
             * @default 0
             */
            dossiers_complete: number;
            /**
             * Dossiers Failed
             * @default 0
             */
            dossiers_failed: number;
        };
        /**
         * SceneOut
         * @description Mirrors the `Scene` interface in web/lib/api-types.ts.
         */
        SceneOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Script Id
             * Format: uuid
             */
            script_id: string;
            /** Number */
            number: number;
            /** Int Ext */
            int_ext: ("INT" | "EXT" | "INT/EXT") | null;
            /** Location */
            location: string | null;
            /** Time Of Day */
            time_of_day: string | null;
            /** Heading */
            heading: string;
            /** Page Start */
            page_start: number;
            /** Page End */
            page_end: number;
            /** Elements */
            elements: components["schemas"]["ScriptElementOut"][];
        };
        /**
         * ScenesOut
         * @description The scenes endpoint returns an object, not a bare array.
         */
        ScenesOut: {
            /** Scenes */
            scenes: components["schemas"]["SceneOut"][];
        };
        /**
         * ScriptElementOut
         * @description Mirrors the `ScriptElement` interface in web/lib/api-types.ts.
         */
        ScriptElementOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Scene Id
             * Format: uuid
             */
            scene_id: string;
            /** Seq */
            seq: number;
            /**
             * Type
             * @enum {string}
             */
            type: "scene_heading" | "action" | "character" | "dialogue" | "parenthetical" | "transition";
            /** Character */
            character: string | null;
            /** Page */
            page: number;
            /** Text */
            text: string;
        };
        /**
         * ScriptOut
         * @description Mirrors the `Script` interface in web/lib/api-types.ts.
         */
        ScriptOut: {
            /**
             * Script Id
             * Format: uuid
             */
            script_id: string;
            /** Title */
            title: string;
            /**
             * Source Format
             * @enum {string}
             */
            source_format: "pdf" | "fdx" | "fountain";
            /** Page Count */
            page_count: number;
            /** Scene Count */
            scene_count: number;
            /** Parse Warnings */
            parse_warnings: string[];
            /** Duplicate Of */
            duplicate_of: string | null;
        };
        /**
         * ScriptRunOut
         * @description The most recent run over a script, or nothing if it has never been run.
         *
         *     Denormalised onto the list row on purpose. The sidebar shows a dot per
         *     script — never run, working, done, failed — and doing that with one request
         *     per script would be N+1 queries to render a list.
         */
        ScriptRunOut: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "extracting" | "researching" | "assessing" | "composing" | "complete" | "failed";
            /** Findings */
            findings: number;
            /** Started At */
            started_at: string;
        };
        /**
         * ScriptSummaryOut
         * @description One row in the scripts sidebar. Deliberately not `ScriptOut`.
         *
         *     `ScriptOut` carries `parse_warnings` and `duplicate_of`, which the detail
         *     view needs and a list does not; sending them for every script would grow
         *     the payload with text nobody reads. What a list row needs is enough to
         *     label itself and enough to say what state it is in.
         */
        ScriptSummaryOut: {
            /**
             * Script Id
             * Format: uuid
             */
            script_id: string;
            /** Title */
            title: string;
            /** Page Count */
            page_count: number;
            /** Scene Count */
            scene_count: number;
            /** Uploaded At */
            uploaded_at: string;
            latest_run: components["schemas"]["ScriptRunOut"] | null;
        };
        /**
         * ScriptsOut
         * @description An object, not a bare array, matching ScenesOut.
         *
         *     A top-level JSON array cannot grow a field later without breaking every
         *     client; an object can.
         */
        ScriptsOut: {
            /** Scripts */
            scripts: components["schemas"]["ScriptSummaryOut"][];
        };
        /** SourceOut */
        SourceOut: {
            /** Id */
            id: string;
            /** Claim */
            claim: string;
            /** Url */
            url: string;
            /** Title */
            title: string;
            /** Excerpt */
            excerpt: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_scripts_api_scripts_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScriptsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_script_api_scripts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_script_api_scripts_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScriptOut"];
                };
            };
            /** @description File exceeds the 25 MB cap */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorOut"];
                };
            };
            /** @description Not a PDF */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorOut"];
                };
            };
            /** @description Scanned PDF (NO_TEXT_LAYER), or unparseable */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoTextLayerOut"] | components["schemas"]["ApiErrorOut"];
                };
            };
        };
    };
    get_scenes_api_scripts__id__scenes_get: {
        parameters: {
            query?: {
                /** @description First scene number */
                from?: number | null;
                /** @description Last scene number, inclusive */
                to?: number | null;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenesOut"];
                };
            };
            /** @description No such script */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_script_api_scripts__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScriptOut"];
                };
            };
            /** @description No such script */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description File exceeds the 25 MB cap */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorOut"];
                };
            };
            /** @description Not a PDF */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorOut"];
                };
            };
            /** @description Scanned PDF (NO_TEXT_LAYER), or unparseable */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoTextLayerOut"] | components["schemas"]["ApiErrorOut"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description File exceeds the 25 MB cap */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorOut"];
                };
            };
            /** @description Not a PDF */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorOut"];
                };
            };
            /** @description Scanned PDF (NO_TEXT_LAYER), or unparseable */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoTextLayerOut"] | components["schemas"]["ApiErrorOut"];
                };
            };
        };
    };
    get_findings_api_runs__run_id__findings_get: {
        parameters: {
            query?: {
                /** @description red, amber or green */
                risk?: string | null;
                review_status?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingsOut"];
                };
            };
            /** @description File exceeds the 25 MB cap */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorOut"];
                };
            };
            /** @description Not a PDF */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorOut"];
                };
            };
            /** @description Scanned PDF (NO_TEXT_LAYER), or unparseable */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoTextLayerOut"] | components["schemas"]["ApiErrorOut"];
                };
            };
        };
    };
    get_report_api_runs__run_id__report_get: {
        parameters: {
            query?: {
                /** @description Only pdf, for now. */
                format?: "pdf";
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The clearance report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
            /** @description File exceeds the 25 MB cap */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorOut"];
                };
            };
            /** @description Not a PDF */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorOut"];
                };
            };
            /** @description Scanned PDF (NO_TEXT_LAYER), or unparseable */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoTextLayerOut"] | components["schemas"]["ApiErrorOut"];
                };
            };
        };
    };
    review_finding_api_findings__finding_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindingReviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingOut"];
                };
            };
            /** @description File exceeds the 25 MB cap */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorOut"];
                };
            };
            /** @description Not a PDF */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorOut"];
                };
            };
            /** @description Scanned PDF (NO_TEXT_LAYER), or unparseable */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoTextLayerOut"] | components["schemas"]["ApiErrorOut"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
