"""B2 inspection — show a screenplay's margin geometry, and sanity-check it.

    python api/scripts/verify_b2.py                    # the test fixture
    python api/scripts/verify_b2.py path/to/script.pdf # any other script

"""

from __future__ import annotations

import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))

from api.app.parser.pdf import Line, extract_lines  # noqa: E402

# Two x0 values within this many points are the same margin. Real scripts
# have sub-point jitter; a fixture generated by code does not.
CLUSTER_TOLERANCE = 3.0

results: list[bool] = []


def check(name: str, ok: bool, note: str = "") -> None:
    results.append(ok)
    print(f"[{'PASS' if ok else 'FAIL'}] {name}" + (f" — {note}" if note else ""))


def cluster(values: list[float], tolerance: float = CLUSTER_TOLERANCE) -> dict[float, int]:
    """Group nearby x0 values. Key is the smallest value in each group."""
    counts = Counter(values)
    groups: dict[float, int] = {}
    anchor: float | None = None
    for value in sorted(counts):
        if anchor is None or value - anchor > tolerance:
            anchor = value
        groups[anchor] = groups.get(anchor, 0) + counts[value]
    return groups


def looks_like_cue(line: Line) -> bool:
    """A character cue: short, ALL CAPS, not a slug line."""
    words = line.text.split()
    return (
        line.text.isupper()
        and 1 <= len(words) <= 4
        and not line.text.startswith(("INT", "EXT", "I/E"))
        and any(c.isalpha() for c in line.text)
    )


def main() -> int:
    target = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "docs" / "test_screenplay.pdf"
    if not target.exists():
        print(f"No such file: {target}")
        return 2

    lines = extract_lines(target)
    pages = {line.page for line in lines}
    print(f"\n{target.name} — {len(lines)} lines across {len(pages)} pages\n")

    groups = cluster([line.x0 for line in lines])
    widest = max(groups.values())

    print("MARGIN HISTOGRAM")
    print(f"{'x0 (pt)':>9} {'inches':>7} {'lines':>6}  sample")
    for x0 in sorted(groups):
        members = [ln for ln in lines if abs(ln.x0 - x0) <= CLUSTER_TOLERANCE]
        bar = "#" * max(1, round(groups[x0] * 24 / widest))
        sample = members[0].text[:44] if members else ""
        print(f"{x0:>9.1f} {x0 / 72:>7.2f} {groups[x0]:>6}  {bar}")
        print(f"{'':>25}  {sample!r}")

    # ── sanity checks ──────────────────────────────────────────────────
    print()
    check("Lines were extracted", bool(lines), f"{len(lines)} lines")
    expected = set(range(1, max(pages) + 1))
    gaps = sorted(expected - pages)
    check("Every page contributed lines", not gaps,
          f"{len(pages)} pages" + (f", missing {gaps[:8]}" if gaps else ""))
    check("No empty or whitespace-only text", all(ln.text.strip() for ln in lines))
    check("x1 is always right of x0", all(ln.x1 > ln.x0 for ln in lines))
    check("At least three distinct margins", len(groups) >= 3, f"{len(groups)} clusters")

    cues = [ln for ln in lines if looks_like_cue(ln)]
    prose = [ln for ln in lines if not ln.text.isupper() and len(ln.text.split()) > 4]
    if cues and prose:
        cue_x0 = sorted(ln.x0 for ln in cues)[len(cues) // 2]
        prose_x0 = sorted(ln.x0 for ln in prose)[len(prose) // 2]
        check("Character cues sit right of body text", cue_x0 > prose_x0,
              f"cue x0={cue_x0} vs body x0={prose_x0}")
    else:
        check("Character cues sit right of body text", False,
              f"could not identify both (cues={len(cues)}, prose={len(prose)})")

    print(f"\n{sum(results)}/{len(results)} checks passed")
    print("\nRead the histogram above. The clusters are the margins B4 classifies on.")
    return 0 if all(results) else 1


if __name__ == "__main__":
    sys.exit(main())